Config/summary update
bcgsc/mavis_config pull request #12
Opened 2022-07-28 23:35 UTC by zhemingfan

Update configuration setting to include a parameter allowing users to customize distance by which breakpoints will match the DGV input file.

2022-07-28 23:41 UTC, creisle requested changes

2022-07-28 23:41 UTC, creisle commented on src/mavis_config/config.json
> +            "description": "Maximum distance allowed between breakpoint pairs of called SVs and those of known SVs",
you may need to be more explicit here, like "Distance used in matching input SVs to reference SVs through clustering"

2022-07-28 23:41 UTC, creisle commented on src/mavis_config/config.json
> +            "type": "integer"
You should specify a minimum of 0 here so we don't get nonsensical negative inputs

2022-07-28 23:42 UTC, creisle commented
I thought you were adding validate.assembler?

2022-07-28 23:47 UTC, zhemingfan commented
> I thought you were adding validate.assembler, is that going to be in a separate PR? also redbeans to validate.aligner enum

That'll be in a separate PR.

2022-07-28 23:52 UTC, creisle requested changes

2022-07-28 23:52 UTC, creisle commented on src/mavis_config/config.json
> +            "type": "integer"
I think you may have misunderstood. The default can stay as 10, but you can add a new field "minimum": 0 

see spec docs here https://json-schema.org/understanding-json-schema/reference/numeric.html#range

2022-07-29 20:48 UTC, creisle approved these changes

2022-07-29 20:56 UTC, merged